# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish To registries

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x
            - run: npm ci
            - run: npm test
    package:
        needs: [build]
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x
            - run: npm ci
            - run: npm version prerelease --preid=ci-$GITHUB_RUN_ID --no-git-tag-version
            - run: npm pack
            - name: Upload
              uses: actions/upload-artifact@v2
              with:
                  name: package
                  path: "*.tgz"
    publish:
        name: "Publish to GitHub Packages"
        needs: [package]
        runs-on: ubuntu-18.04
        if: github.repository_owner == 'undefinedfn'
        steps:
            - name: Upload
              uses: actions/download-artifact@v2
              with:
                  name: package
            - uses: actions/setup-node@v1
              with:
                  node-version: 14.x
                  registry-url: https://npm.pkg.github.com/
                  scope: "@aaronpowell"
            - run: echo "registry=https://npm.pkg.github.com/@undefinedfn" >> .npmrc
            - run: npm publish $(ls *.tgz)
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
